### 타이타닉 데이터 실습

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [9]:
df["SibSp"].corr(df["Parch"])

np.float64(0.41483769862015646)

In [10]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [11]:
df.select_dtypes(include='number').corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [12]:
df[["SibSp", "Parch", "Fare"]].corr()

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [13]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [14]:
df.std(numeric_only=True)

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [15]:
df.groupby("Survived").mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [16]:
df.groupby(["Sex", "Survived"]).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [17]:
df1 = df.rename({"Name":"이름"}, axis=1)
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [18]:
df2 = df.rename(columns={"Age":"나이"})
df2.head(1)

,PassengerId,Survived,Pclass,Name,Sex,나이,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [19]:
df3 = df.Sex.map(lambda x : 0 if x == "female" else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [20]:
def n_square(x):
    return x ** 2

In [21]:
df4_1 = df["Age"].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [22]:
def n_square(x, n):
    return x ** n

In [23]:
df4 = df[["Age",  "SibSp", "Fare"]].apply(n_square, n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

### 객체 연산

In [24]:
data = [[1,10,100],[2,20,200],[3,30,300]]
col = ['col1','col2','col3']
row = ['row1','row2','row3']
df = pd.DataFrame(data=data, index=row, columns=col)
df

      col1  col2  col3
row1     1    10   100
row2     2    20   200
row3     3    30   300

In [25]:
result = df.add(1) # sub(). mul(), div(), mod()
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [26]:
result = df + 1
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [27]:
data2  = [[3],[4],[5]]
df2 = pd.DataFrame(data=data2, index=['row1','row2','row3'], columns=['col1'])
df2

      col1
row1     3
row2     4
row3     5

In [28]:
result = df.add(df2)
result

      col1  col2  col3
row1     4   NaN   NaN
row2     6   NaN   NaN
row3     8   NaN   NaN

In [29]:
result = df.add(df2,fill_value=1) # df2에 없는 컬럼에 0을 채워서 연산
result

      col1  col2   col3
row1     4  11.0  101.0
row2     6  21.0  201.0
row3     8  31.0  301.0

In [30]:
col = ['col1','col2']
row = ['row1','row2']
data1 = [[1,2],[3,4]]
data2 = [[5,6],[7,8]]
df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [31]:
df1

   0  1
0  1  2
1  3  4

In [32]:
df2

   0  1
0  5  6
1  7  8

In [33]:
df3 = df1.dot(df2)
df3

    0   1
0  19  22
1  43  50

In [34]:
import numpy as np

col = ['col1','col2','col3']
row = ['row1','row2','row3']
data = np.random.rand(3,3)*100
df = pd.DataFrame(data=data, index=row, columns=col)
df

           col1       col2       col3
row1  89.518660  50.022921  38.522101
row2  60.806843   5.363068  62.184628
row3  62.360481  24.077161  33.582511

In [35]:
df.round(0)

      col1  col2  col3
row1  90.0  50.0  39.0
row2  61.0   5.0  62.0
row3  62.0  24.0  34.0

In [36]:
df.round(2)

       col1   col2   col3
row1  89.52  50.02  38.52
row2  60.81   5.36  62.18
row3  62.36  24.08  33.58

In [37]:
import numpy as np

col = ['col1','col2','col3']
row = ['row1','row2','row3']
data = [[1,2,3],[4,5,6],[7,np.nan,9]]
df = pd.DataFrame(data=data, index=row, columns=col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [38]:
df.sum(axis=0)

col1    12.0
col2     7.0
col3    18.0
dtype: float64

In [39]:
df.sum(axis=1)

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [40]:
df.sum(axis=0,skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [41]:
df.prod(axis=0)

col1     28.0
col2     10.0
col3    162.0
dtype: float64

In [42]:
df.prod(axis=1)

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [43]:
df.prod(axis=0, skipna=False)

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [44]:
df.transpose()

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [45]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [46]:
idx=['A','A','B','B','B','C','C','C','D','D','D','D','E','E','E']
col=['col1','col2','col3']
data = np.random.randint(0,9,(15,3))
df = pd.DataFrame(data=data, index=idx, columns=col).reset_index()
df

   index  col1  col2  col3
0      A     0     6     6
1      A     5     1     0
2      B     0     4     6
3      B     0     1     8
4      B     4     7     5
5      C     8     1     8
6      C     6     1     4
7      C     4     6     2
8      D     3     8     4
9      D     0     3     4
10     D     4     7     2
11     D     2     2     0
12     E     3     5     4
13     E     7     2     0
14     E     1     5     7

In [47]:
df.groupby('index').mean()

           col1      col2      col3
index
A      2.500000  3.500000  3.000000
B      1.333333  4.000000  6.333333
C      6.000000  2.666667  4.666667
D      2.250000  5.000000  2.500000
E      3.666667  4.000000  3.666667

In [48]:
df.groupby('index').count()

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [49]:
df.groupby('index').agg(['sum','mean'])

      col1           col2           col3
       sum      mean  sum      mean  sum      mean
index
A        5  2.500000    7  3.500000    6  3.000000
B        4  1.333333   12  4.000000   19  6.333333
C       18  6.000000    8  2.666667   14  4.666667
D        9  2.250000   20  5.000000   10  2.500000
E       11  3.666667   12  4.000000   11  3.666667

In [50]:
period = pd.period_range(start='2022-01-13 00:00:00',end='2022-01-13 02:30:00',freq='30min')
data = {'col1':[1,2,3,4,5,6],'col2':period}
idx = ['row1','row2','row3','row4','row5','row6']
df = pd.DataFrame(data= data, index = idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [51]:
df.rolling(window=3).sum(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [52]:
df.rolling(window=4).mean(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   NaN
row4   2.5
row5   3.5
row6   4.5

In [53]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}

column_list  = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index_list = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index_list, columns=column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [54]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [55]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [56]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='str')

In [57]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [58]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [59]:
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [60]:
df.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [61]:
df[["2010", "2015"]]

특성     2010     2015
도시
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [62]:
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [63]:
df[["지역"]]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [64]:
type(df[["지역"]])

pandas.DataFrame

In [65]:
type(df["지역"])

pandas.Series

In [66]:
import numpy as np

df2 = pd.DataFrame(np.arange(12).reshape(3, 4)) # np.arange()와 range()함수는 동일하게 동작한다.
df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [67]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [68]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [69]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [70]:
del df["2010-2015 증가율"] # df.drop("2010-2015 증가율", axis=1)
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [71]:
df3 = df.drop("2005-2010 증가율", axis=1)
df3

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9631482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473990

In [72]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [73]:
df3 = df.drop("서울", axis=0)
df3

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [74]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [75]:
df["2015"]["서울"]

np.int64(9904312)

In [76]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [77]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [78]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [79]:
df[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [80]:
df.iloc[[0, 2]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [81]:
df.iloc[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [82]:
df.loc[["서울", "부산"]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [83]:
df.loc["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [84]:
s1 = pd.Series([0,1],index=['A','B'])
s1

A    0
B    1
dtype: int64

In [85]:
s2 = pd.Series([2,3,4],index=['A','B','C'])
s2

A    2
B    3
C    4
dtype: int64

In [86]:
s3 = pd.concat([s1,s2])
s3

A    0
B    1
A    2
B    3
C    4
dtype: int64

In [87]:
s3 = pd.concat([s1,s2], axis=1)
s3

     0  1
A  0.0  2
B  1.0  3
C  NaN  4

In [88]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2),
    index=['a','b','c'],
    columns=['데이터1','데이터2'])
df1

   데이터1  데이터2
a     0     1
b     2     3
c     4     5

In [89]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),
    index=['a','c'],
    columns=['데이터3','데이터4'])
df2

   데이터3  데이터4
a     5     6
c     7     8

In [90]:
df3 = pd.concat([df1,df2])
df3

   데이터1  데이터2  데이터3  데이터4
a   0.0   1.0   NaN   NaN
b   2.0   3.0   NaN   NaN
c   4.0   5.0   NaN   NaN
a   NaN   NaN   5.0   6.0
c   NaN   NaN   7.0   8.0

In [91]:
df3 = pd.concat([df1,df2],axis=1)
df3

   데이터1  데이터2  데이터3  데이터4
a     0     1   5.0   6.0
b     2     3   NaN   NaN
c     4     5   7.0   8.0

In [92]:
df1 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                  index=['a','c','e'],
                  columns=['서울','부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [93]:
df2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                  index=['b','c','d','e'],
                  columns=['대구','광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [94]:
df3 = df1.join(df2,how='outer')
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [95]:
df4 = df1.join(df2,how='inner')
df4

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0

In [96]:
df5 = df1.join(df2,how='right')
df5

    서울   부산    대구    광주
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [97]:
import numpy as np

n=np.nan
idx= ['row1','row2','row3']
col= ['col1','col2','col3']
data = [[1,2,200],[100,5,6],[7,300,n]]
df = pd.DataFrame(data,idx,col)
df

      col1  col2   col3
row1     1     2  200.0
row2   100     5    6.0
row3     7   300    NaN

In [98]:
df.idxmax(axis=0)

col1    row2
col2    row3
col3    row1
dtype: str

In [99]:
df.idxmax(axis=1)

row1    col3
row2    col1
row3    col2
dtype: str

In [100]:
df.idxmin(axis=0,skipna=True)

col1    row1
col2    row1
col3    row2
dtype: str

In [101]:
df.idxmin(axis=1)

row1    col1
row2    col2
row3    col1
dtype: str

### 시계열 데이터

In [102]:
data_str = ["2018, 1, 1","2018, 1, 4","2018, 1, 5"]
idx = pd.to_datetime(data_str)
idx

DatetimeIndex(['2018-01-01', '2018-01-04', '2018-01-05'], dtype='datetime64[us]', freq=None)

In [103]:
np.random.seed(0)
s = pd.Series(np.random.randn(3), index = idx)
s

2018-01-01    1.764052
2018-01-04    0.400157
2018-01-05    0.978738
dtype: float64

In [104]:
pd.date_range("2020-7-1","2020-7-30")

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [105]:
pd.date_range(start="2020-7-1",end="2020-7-30")

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [106]:
pd.date_range(start="2020-7-1",periods= 7)

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07'],
              dtype='datetime64[us]', freq='D')

In [107]:
pd.date_range(start="2020-7-1",periods= 7, freq='s')

DatetimeIndex(['2020-07-01 00:00:00', '2020-07-01 00:00:01',
               '2020-07-01 00:00:02', '2020-07-01 00:00:03',
               '2020-07-01 00:00:04', '2020-07-01 00:00:05',
               '2020-07-01 00:00:06'],
              dtype='datetime64[us]', freq='s')

In [108]:
pd.date_range("2026-1-1","2026-12-31", freq='W-SUN')

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08', '2026-02-15', '2026-02-22',
               '2026-03-01', '2026-03-08', '2026-03-15', '2026-03-22',
               '2026-03-29', '2026-04-05', '2026-04-12', '2026-04-19',
               '2026-04-26', '2026-05-03', '2026-05-10', '2026-05-17',
               '2026-05-24', '2026-05-31', '2026-06-07', '2026-06-14',
               '2026-06-21', '2026-06-28', '2026-07-05', '2026-07-12',
               '2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09',
               '2026-08-16', '2026-08-23', '2026-08-30', '2026-09-06',
               '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04',
               '2026-10-11', '2026-10-18', '2026-10-25', '2026-11-01',
               '2026-11-08', '2026-11-15', '2026-11-22', '2026-11-29',
               '2026-12-06', '2026-12-13', '2026-12-20', '2026-12-27'],
              dtype='datetime64[us]', freq='W-SUN')

In [109]:
pd.date_range("2026-1-1","2026-12-31", freq='W-FRI')

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06', '2026-02-13', '2026-02-20',
               '2026-02-27', '2026-03-06', '2026-03-13', '2026-03-20',
               '2026-03-27', '2026-04-03', '2026-04-10', '2026-04-17',
               '2026-04-24', '2026-05-01', '2026-05-08', '2026-05-15',
               '2026-05-22', '2026-05-29', '2026-06-05', '2026-06-12',
               '2026-06-19', '2026-06-26', '2026-07-03', '2026-07-10',
               '2026-07-17', '2026-07-24', '2026-07-31', '2026-08-07',
               '2026-08-14', '2026-08-21', '2026-08-28', '2026-09-04',
               '2026-09-11', '2026-09-18', '2026-09-25', '2026-10-02',
               '2026-10-09', '2026-10-16', '2026-10-23', '2026-10-30',
               '2026-11-06', '2026-11-13', '2026-11-20', '2026-11-27',
               '2026-12-04', '2026-12-11', '2026-12-18', '2026-12-25'],
              dtype='datetime64[us]', freq='W-FRI')

In [110]:
pd.date_range("2026-1-1","2026-12-31",freq='B')

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14',
               ...
               '2026-12-18', '2026-12-21', '2026-12-22', '2026-12-23',
               '2026-12-24', '2026-12-25', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=261, freq='B')

In [111]:
pd.date_range("2026-1-1","2026-12-31",freq='MS')

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'],
              dtype='datetime64[us]', freq='MS')

In [112]:
pd.date_range("2026-1-1","2026-12-31",freq='ME')

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[us]', freq='ME')

In [113]:
pd.date_range("2026-1-1","2026-12-31",freq='WOM-2SUN')

DatetimeIndex(['2026-01-11', '2026-02-08', '2026-03-08', '2026-04-12',
               '2026-05-10', '2026-06-14', '2026-07-12', '2026-08-09',
               '2026-09-13', '2026-10-11', '2026-11-08', '2026-12-13'],
              dtype='datetime64[us]', freq='WOM-2SUN')

In [114]:
pd.date_range("2026-1-1","2026-12-31",freq='QE-JAN')

DatetimeIndex(['2026-01-31', '2026-04-30', '2026-07-31', '2026-10-31'], dtype='datetime64[us]', freq='QE-JAN')

In [115]:
sample1 = pd.read_csv('sample1.csv')
sample1

FileNotFoundError: [Errno 2] No such file or directory: 'sample1.csv'

In [ ]:
sample2 = pd.read_csv('sample2.csv', names=['c1','c2','c3'])
sample2

In [ ]:
sample1 = pd.read_csv('sample1.csv', index_col='c1')
sample1

In [ ]:
sample3 = pd.read_table('sample3.txt', sep='\t')
sample3

In [ ]:
sample4 = pd.read_csv('sample4.txt',skiprows=[0,1])
sample4

In [ ]:
sample5 = pd.read_csv('sample5.csv', na_values=['누락'])
sample5

In [ ]:
df = pd.read_csv('sample5.csv', na_values=['누락'])
df.to_csv('sample6.csv')

In [ ]:
df.to_csv('sample7.txt', sep = '|')

In [ ]:
df.to_csv('sample8.csv', na_rep='없음')

In [ ]:
df.to_csv('sample9.csv', index= False, header=True )

In [ ]:
df.index = ['a','b','c']
df.to_csv('sample10.csv', index= True, header=False )

### 함수 더

In [ ]:
[N,T,F] = [np.nan,True,False]
df
idx=[['IDX1','IDX1','IDX2','IDX2'],['row1','row2','row3','row4']]
col = [['COL1','COL1','COL2','COL2'],['val1','val2','val3','val4']]
data = [[N,13,3,4],[5,7,10,8],[15,6,N,3],[2,14,9,1]]
df = pd.DataFrame(data,idx,col)
df

In [ ]:
df.max(axis = 0)

In [ ]:
df.max(axis = 1)

In [ ]:
df.max(skipna = True)

In [ ]:
df.max(skipna = False)

In [ ]:
df.min(skipna = False)

In [ ]:
df.mean(axis=0)

In [ ]:
df.median(axis=0)

In [ ]:
df.mode(axis=0)

In [ ]:
df.std(axis=0)

In [ ]:
df.var(axis=0)

In [ ]:
col1 = [1,2,3,4,5,6]
col2 = [1,4,2,8,16,32]
col3 = [6,5,4,3,2,1]
data = {"col1":col1,"col2":col2,"col3":col3}
df = pd.DataFrame(data)
df

In [ ]:
df.corr(method='pearson', numeric_only = True)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('./titanic/train.csv')
df.head(2)

In [ ]:
df.sort_index(ascending=False)

In [ ]:
df.sort_values(by='Pclass',ascending=False)

In [ ]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632035],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ['도시','연도','인구','지역']
df1 = pd.DataFrame(data,columns=columns)
df1

In [ ]:
# index, columns, value
df1.pivot(index="도시",columns="연도",values="인구")

### pivot_table
형식) pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, margins_name='All')
- data: 분석할 데이터프레임 (메서드일 때는 필요하지 않음)
- values: 분석할 데이터프레임에서 분석할 열
- index: 행 인덱스로 들어갈 키 열 또는 키 열의 리스트
- columns: 열 인덱스로 들어갈 키 열 또는 키 열의 리스트
- aggfunc: 분석 메서드 지정
- fill_value: NaN 대체 값 설정
- margins: 오른쪽과 아래에 합계를 붙일지 여부 지정
- margins_name: 합계 열(행)의 이름 지정

In [ ]:
df2 = pd.DataFrame({'key1': ['A','A','B','B','A'],
                   'key2' : ['one','two','one','two','one'],
                   'data1' : [1,2,3,4,5],
                   'data2' : [10,20,30,40,50]})
df2

In [ ]:
df2.pivot_table('data1','key1','key2') # default aggfunc='mean'

In [ ]:
df2.pivot_table('data1','key1','key2', aggfunc= 'sum')

In [ ]:
df2.pivot_table('data1','key1','key2', margins=True)

In [ ]:
df2.pivot_table('data1','key1','key2', margins=True, margins_name='평균')

In [ ]:
df2.pivot_table('data1',index=['key1','key2'])

### 추가 라이브러리
- pip install matplotlib
- pip install seaborn
- pip install scipy

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family']= 'Malgun Gothic'    # 폰트 설정 한글
plt.rcParams['axes.unicode_minus'] = False     # 마이너스 문제 해결

In [ ]:
df = pd.DataFrame({'col1': [1,-2,5,3,-1,7],'col2': [3,4,np.nan,9,2,5]})
df

In [ ]:
df.cumsum(skipna=False)

In [ ]:
np.random.seed(0)
df1 = pd.DataFrame(np.random.randn(100,3),
                  index=pd.date_range('1/1/2018',periods=100),
                  columns=['A','B','C']).cumsum()
df1.tail(3)

In [ ]:
df1.plot(kind='line')
plt.title("Pandas의 Plot메소드 사용 예")
plt.xlabel("시간")
plt.ylabel("Data")
plt.show()

In [ ]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import seaborn as sns

iris = sns.load_dataset("iris")
iris

In [ ]:
iris.sepal_length[:20].plot(kind='bar',rot=0)
plt.title('꽃받침의 길이 시각화')
plt.xlabel('data')
plt.ylabel('꽃받침의 길이')
plt.show()

In [ ]:
iris[:5].plot.bar(rot=0)
plt.title('Iris 데이터의 Bar Plot')
plt.xlabel('Data')
plt.ylabel('각 Feature의 값')
plt.show()

In [ ]:
df2 =iris.groupby(iris.species).mean()
df2.columns.name = "feature"
df2

In [ ]:
df2.plot.bar(rot=0)
plt.title('각 종의 Feature별 평균')
plt.xlabel('평균')
plt.ylabel('종')
plt.ylim(0,8)
plt.show()

In [ ]:
titanic = sns.load_dataset("titanic")
titanic.head(2)

In [ ]:
df3 = titanic.pclass.value_counts()
df3

In [ ]:
df3.plot.pie(autopct='%.2f%%')
plt.title("선실별 승객 수 비율")
plt.axis('equal')
plt.show()

In [ ]:
iris.plot.box()
plt.title('각 Feature 값들의 빈도수에 대한 Box Plot')
plt.xlabel("Feature")
plt.ylabel("데이터 값")
plt.show

In [ ]:
iris.boxplot(by='species')
plt.tight_layout(pad=3,h_pad=1)
plt.title('각 Feature의 종 별 데이터에 대한 Box Plot')
plt.show()