In [11]:
import pandas as pd

file_path = '포항시남구표제부1.csv'

try:
    df = pd.read_csv(file_path, encoding='cp949', dtype={'법정동코드': str, '번': str, '지': str})
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='utf-8', dtype={'법정동코드': str, '번': str, '지': str})

df['법정동코드'] = df['법정동코드'].fillna('')
df['번'] = df['번'].fillna('')
df['지'] = df['지'].fillna('')

df['관리번호_PK'] = df['법정동코드'] + '-' + df['번'] + '-' + df['지']

# 중복 데이터 제거! ★ (이 부분이 추가되었습니다)
# subset=['관리번호_PK']: 이 컬럼을 기준으로 중복 검사
# keep='first': 중복된 행 중 맨 처음에 나온 데이터만 남기고 삭제
original_count = len(df)
df = df.drop_duplicates(subset=['관리번호_PK'], keep='first')
new_count = len(df)
print(f"✔️ 중복 제거 완료: 총 {original_count}개 중 {original_count - new_count}개의 중복 데이터가 삭제되어 {new_count}개만 남았습니다.\n")

df = df.drop(columns=['법정동코드', '번', '지'])

cols = ['관리번호_PK'] + [col for col in df.columns if col != '관리번호_PK']
df = df[cols]

# 결과 확인
print("기존 컬럼이 지워지고 PK가 맨 앞에 잘 배치되었는지 확인해 보세요:")
display(df.head())

output_path = '포항남구표제부_PK추가_clean.csv'
df.to_csv(output_path, encoding='utf-8-sig', index=False)

print(f"\n변환 완료! '{output_path}' 파일이 생성되었습니다.")

✔️ 중복 제거 완료: 총 45045개 중 10709개의 중복 데이터가 삭제되어 34336개만 남았습니다.

기존 컬럼이 지워지고 PK가 맨 앞에 잘 배치되었는지 확인해 보세요:

           관리번호_PK   연면적(㎡)     주용도코드명  세대수(세대)  가구수(가구)  착공일
0  10100-0001-0002  2676.60       공동주택       40        0  NaN
2  10100-0001-0004   133.20       단독주택        0        2  NaN
3  10100-0001-0007    96.54       단독주택        0        1  NaN
4  10100-0001-0008   167.56       단독주택        0        2  NaN
5  10100-0001-0009   493.92  제2종근린생활시설        0        1  NaN

변환 완료! '포항남구표제부_PK추가_clean.csv' 파일이 생성되었습니다.

In [12]:
import pandas as pd

file_path = '포항시남구전기202606.csv'

try:
    df = pd.read_csv(file_path, encoding='cp949', dtype={'법정동코드': str, '번': str, '지': str})
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='utf-8', dtype={'법정동코드': str, '번': str, '지': str})

df['법정동코드'] = df['법정동코드'].fillna('')
df['번'] = df['번'].fillna('')
df['지'] = df['지'].fillna('')

df['관리번호_PK'] = df['법정동코드'] + '-' + df['번'] + '-' + df['지']

df = df.drop(columns=['법정동코드', '번', '지'])

df.rename(columns={'사용량(KWh)': '사용량_KWh'}, inplace=True)

cols = ['관리번호_PK'] + [col for col in df.columns if col != '관리번호_PK']
df = df[cols]

print("전기 사용량 데이터 PK 생성 완료:")
display(df.head())

output_path = '포항남구전기_PK추가_clean.csv'
df.to_csv(output_path, encoding='utf-8-sig', index=False)

print(f"\n변환 완료! '{output_path}' 파일이 생성되었습니다.")

전기 사용량 데이터 PK 생성 완료:

           관리번호_PK    사용년월  사용량_KWh
0  10100-0001-0009  202506      727
1  10100-0001-0012  202506     9940
2  10100-0001-0013  202506      264
3  10100-0001-0017  202506      173
4  10100-0001-0022  202506      804

변환 완료! '포항남구전기_PK추가_clean.csv' 파일이 생성되었습니다.

In [3]:
import pandas as pd

file_path = '포항시남구전기2025.csv'

try:
    df = pd.read_csv(file_path, encoding='cp949', dtype={'법정동코드': str, '번': str, '지': str})
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='utf-8', dtype={'법정동코드': str, '번': str, '지': str})

df['법정동코드'] = df['법정동코드'].fillna('')
df['번'] = df['번'].fillna('')
df['지'] = df['지'].fillna('')

df['관리번호_PK'] = df['법정동코드'] + '-' + df['번'] + '-' + df['지']

df = df.drop(columns=['법정동코드', '번', '지'])

df.rename(columns={'사용량(KWh)': '사용량_KWh'}, inplace=True)

cols = ['관리번호_PK'] + [col for col in df.columns if col != '관리번호_PK']
df = df[cols]

print("전기 사용량 데이터 PK 생성 완료:")
display(df.head())

output_path = '포항남구전기2025_PK추가_clean.csv'
df.to_csv(output_path, encoding='utf-8-sig', index=False)

print(f"\n변환 완료! '{output_path}' 파일이 생성되었습니다.")

전기 사용량 데이터 PK 생성 완료:

           관리번호_PK    사용년월  사용량_KWh
0  10100-0001-0009  202501     3377
1  10100-0001-0009  202502     3542
2  10100-0001-0009  202503     2656
3  10100-0001-0009  202504     1634
4  10100-0001-0009  202505      732

변환 완료! '포항남구전기2025_PK추가_clean.csv' 파일이 생성되었습니다.

In [4]:
import pandas as pd

file_path = '포항시남구가스2025.csv'

try:
    df = pd.read_csv(file_path, encoding='cp949', dtype={'법정동코드': str, '번': str, '지': str})
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='utf-8', dtype={'법정동코드': str, '번': str, '지': str})

df['법정동코드'] = df['법정동코드'].fillna('')
df['번'] = df['번'].fillna('')
df['지'] = df['지'].fillna('')

df['관리번호_PK'] = df['법정동코드'] + '-' + df['번'] + '-' + df['지']

df = df.drop(columns=['법정동코드', '번', '지'])

df.rename(columns={'사용량(KWh)': '사용량_KWh'}, inplace=True)

cols = ['관리번호_PK'] + [col for col in df.columns if col != '관리번호_PK']
df = df[cols]

print("가스 사용량 데이터 PK 생성 완료:")
display(df.head())

output_path = '포항남구가스2025_PK추가_clean.csv'
df.to_csv(output_path, encoding='utf-8-sig', index=False)

print(f"\n변환 완료! '{output_path}' 파일이 생성되었습니다.")

가스 사용량 데이터 PK 생성 완료:

           관리번호_PK    사용년월  사용량_KWh
0  10100-0001-0022  202501     1741
1  10100-0001-0022  202502     2642
2  10100-0001-0022  202503     3229
3  10100-0001-0022  202504     1380
4  10100-0001-0022  202505      575

변환 완료! '포항남구가스2025_PK추가_clean.csv' 파일이 생성되었습니다.